# version: '3.3'

# volumes:
#   pg_data:
#   static:
#   media:

# services:
#   db:
#     image: postgres:13
#     env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   backend:
#     build: ../backend
#     env_file: .env
#     volumes:
#       - static:/backend_static/
#       - media:/app/media/

#   frontend:
#     image: apollo297/foodgram_frontend
#     volumes:
#       - ../frontend/:/app/result_build/
#     depends_on:
#       - backend

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/
#       - static:/app/static/
#       - media:/app/media/
#     depends_on:
#       - frontend

version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  
  frontend:
    image: apollo297/foodgram_frontend 
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  
  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
      - media:/app/media/
    depends_on:
      - frontend




